"""add_color_hex_column

Revision ID: e50eae02c7d8
Revises: d3e4f5a6b7c8
Create Date: 2026-08-09 22:37:29.844467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e50eae02c7d8'
down_revision: Union[str, Sequence[str], None] = 'd3e4f5a6b7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes_registro_vehiculo', sa.Column('color_hex', sa.String(), nullable=True))
    op.add_column('vehiculos', sa.Column('color_hex', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehiculos', 'color_hex')
    op.drop_column('solicitudes_registro_vehiculo', 'color_hex')
    # ### end Alembic commands ###
